const { Pool } = require('pg');
const dbConfig = require('../config/db.config');

const DATABASE_URL = (process.env.DATABASE_URL || dbConfig.DATABASE_URL || '').trim();
const AUTO_INIT_SCHEMA = String(process.env.DB_AUTO_INIT_SCHEMA || 'true').toLowerCase() !== 'false';

if (!DATABASE_URL) {
  throw new Error([
    'DATABASE_URL belum diset.',
    'Backend ini wajib memakai PostgreSQL untuk integrasi VFlow.',
    'Contoh lokal: DATABASE_URL=postgresql://USER:PASS@127.0.0.1:5432/smart_internship',
    'Contoh VFlow connection pack: postgresql://USER:PASS@db-tunnel.vastar.id:15431/DB_NAME',
    'Jangan memakai SQLite/backend/data.sqlite untuk integrasi VFlow.'
  ].join('\n'));
}

const pool = new Pool({
  connectionString: DATABASE_URL,
  max: Number(process.env.DB_POOL_MAX || 20),
  idleTimeoutMillis: Number(process.env.DB_IDLE_TIMEOUT_MS || 30000),
  connectionTimeoutMillis: Number(process.env.DB_CONNECTION_TIMEOUT_MS || 10000),
  ssl: String(process.env.DB_SSL || '').toLowerCase() === 'true'
    ? { rejectUnauthorized: false }
    : undefined,
});

pool.on('connect', () => {
  console.log('✓ Connected to PostgreSQL database');
});

pool.on('error', (err) => {
  console.error('PostgreSQL pool error:', err.message);
});

function normalizeSql(sql = '') {
  let normalized = sql;

  normalized = normalized.replace(/AUTOINCREMENT/gi, 'GENERATED BY DEFAULT AS IDENTITY');
  normalized = normalized.replace(/MAX\s*\(\s*0\s*,\s*quota\s*-\s*1\s*\)/gi, 'GREATEST(0, quota - 1)');
  normalized = normalized.replace(/datetime\s*\(\s*'now'\s*\)/gi, 'NOW()');
  normalized = normalized.replace(/CURRENT_TIMESTAMP/gi, 'NOW()');

  normalized = normalized.replace(/strftime\s*\(\s*'%m'\s*,\s*created_at\s*\)/gi, "TO_CHAR(created_at, 'MM')");
  normalized = normalized.replace(/strftime\s*\(\s*'%Y-%m'\s*,\s*created_at\s*\)/gi, "TO_CHAR(created_at, 'YYYY-MM')");
  normalized = normalized.replace(/strftime\s*\(\s*'%Y'\s*,\s*created_at\s*\)/gi, "TO_CHAR(created_at, 'YYYY')");

  return normalized;
}

function convertPlaceholders(sql, params = []) {
  let pgSql = normalizeSql(sql);
  let paramIndex = 1;

  for (let i = 0; i < params.length; i += 1) {
    pgSql = pgSql.replace('?', `$${paramIndex}`);
    paramIndex += 1;
  }

  if (/^\s*insert\s+/i.test(pgSql) && !/\sreturning\s+/i.test(pgSql)) {
    pgSql = `${pgSql} RETURNING id`;
  }

  return pgSql;
}

async function run(sql, params = []) {
  try {
    const pgSql = convertPlaceholders(sql, params);
    const result = await pool.query(pgSql, params);

    return {
      id: result.rows?.[0]?.id,
      row: result.rows?.[0],
      rows: result.rows,
      changes: result.rowCount,
      rowCount: result.rowCount,
    };
  } catch (error) {
    console.error('Database run error:', error.message);
    console.error('SQL:', sql);
    console.error('Params:', params);
    throw error;
  }
}

async function get(sql, params = []) {
  try {
    const pgSql = convertPlaceholders(sql, params);
    const result = await pool.query(pgSql, params);
    return result.rows[0] || null;
  } catch (error) {
    console.error('Database get error:', error.message);
    console.error('SQL:', sql);
    console.error('Params:', params);
    throw error;
  }
}

async function all(sql, params = []) {
  try {
    const pgSql = convertPlaceholders(sql, params);
    const result = await pool.query(pgSql, params);
    return result.rows;
  } catch (error) {
    console.error('Database all error:', error.message);
    console.error('SQL:', sql);
    console.error('Params:', params);
    throw error;
  }
}

async function transaction(callback) {
  const client = await pool.connect();

  const wrappedClient = {
    query: (sql, params = []) => client.query(convertPlaceholders(sql, params), params),
    run: async (sql, params = []) => {
      const result = await client.query(convertPlaceholders(sql, params), params);
      return {
        id: result.rows?.[0]?.id,
        row: result.rows?.[0],
        rows: result.rows,
        changes: result.rowCount,
      };
    },
    get: async (sql, params = []) => {
      const result = await client.query(convertPlaceholders(sql, params), params);
      return result.rows[0] || null;
    },
    all: async (sql, params = []) => {
      const result = await client.query(convertPlaceholders(sql, params), params);
      return result.rows;
    },
  };

  try {
    await client.query('BEGIN');
    const result = await callback(wrappedClient);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

async function initSchema() {
  if (!AUTO_INIT_SCHEMA) return;

  const schemaSql = `
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT,
      nim TEXT,
      nip TEXT,
      email TEXT UNIQUE,
      prodi TEXT,
      year TEXT,
      phone TEXT,
      password TEXT,
      role TEXT,
      gpa REAL DEFAULT 0,
      semester INTEGER DEFAULT 1,
      organization_exp INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS companies (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT UNIQUE,
      city TEXT,
      bidang TEXT,
      quota INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS internships (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_email TEXT,
      name TEXT,
      nim TEXT,
      prodi TEXT,
      year TEXT,
      phone TEXT,
      motivation TEXT,
      skills TEXT,
      certificates TEXT,
      documents TEXT,
      status TEXT DEFAULT 'pending',
      progress INTEGER DEFAULT 0,
      company TEXT,
      company_bidang TEXT,
      pembimbing_email TEXT,
      eligibility_score INTEGER DEFAULT 0,
      eligibility_passed INTEGER DEFAULT 0,
      match_score INTEGER DEFAULT 0,
      final_score REAL DEFAULT 0,
      grade TEXT DEFAULT '-',
      certificate_code TEXT,
      vflow_execution_id TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS reports (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      internship_id INTEGER,
      week INTEGER,
      note TEXT,
      file_path TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS feedbacks (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      student_id TEXT,
      internship_id INTEGER,
      score INTEGER,
      comment TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS workflow_logs (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      workflow_name TEXT,
      status TEXT,
      payload TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS assessments (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      internship_id INTEGER,
      assessment_type TEXT,
      score REAL,
      result TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS placements (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      internship_id INTEGER,
      company_id INTEGER,
      company_name TEXT,
      match_score INTEGER,
      status TEXT DEFAULT 'pending',
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS certificates (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      internship_id INTEGER,
      user_email TEXT,
      certificate_code TEXT UNIQUE,
      final_score REAL,
      grade TEXT,
      issued_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS events (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      event_name TEXT,
      payload TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
    CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
    CREATE INDEX IF NOT EXISTS idx_internships_user_email ON internships(user_email);
    CREATE INDEX IF NOT EXISTS idx_internships_status ON internships(status);
    CREATE INDEX IF NOT EXISTS idx_reports_internship_id ON reports(internship_id);
    CREATE INDEX IF NOT EXISTS idx_feedbacks_internship_id ON feedbacks(internship_id);
    CREATE INDEX IF NOT EXISTS idx_workflow_logs_created_at ON workflow_logs(created_at);
  `;

  await pool.query(schemaSql);
  console.log('✓ PostgreSQL schema is ready');
}

async function close() {
  await pool.end();
}

module.exports = {
  db: pool,
  pool,
  run,
  get,
  all,
  transaction,
  initSchema,
  close,
};